### ISSUE TITLE
mc.cores error

### ISSUE THREAD

**Issue by rebrooks406** [nesscoder/TimeCycle#1]
Hi,

I am trying out TimeCycle, and I received the following error:

Error in parallel::mclapply(vect, mc.cores = cores, function(lag) { : 
  'mc.cores' > 1 is not supported on Windows

Is there a workaround for this issue? Thank you!

**Comment by nesscoder** [comment]
Hi @rebrooks406,

There is currently no implemented workaround for TimeCycle to run parallel on a Windows system.

Due to limitations of the parallel package, the parallelization procedure only works on *nix operating systems (including MacOS, Linux, Unix, and BSD), and not Windows. Parallelization is generally necessary when working with dataset with many timepoints (e.g. > 24); in this case, we recommend using parallelization on a linux-based High Performance Computer (HPC) cluster, as was done in the original manuscript.

**Comment by rebrooks406** [comment]
Gotcha--thank you so much for getting back to me!
